package com.swfjunkie.accessibility.impl
{
	
	import flash.events.Event;
	import flash.geom.Rectangle;
	
	import mx.accessibility.AccImpl;
	import mx.core.UIComponent;
	import mx.core.mx_internal;
	
	use namespace mx_internal;
	
	/**
	 *  Custom Accessibility Implementation used by AccLayer
	 */
	public class CustomAccImpl extends AccImpl
	{
		
		//--------------------------------------------------------------------------
		//
		//  Class constants
		//
		//--------------------------------------------------------------------------
        
		//--------------------------------------------------------------------------
		//
		//  Class variables
		//
		//--------------------------------------------------------------------------
        
        //--------------------------------------------------------------------------
        //
        //  Properties
        //
        //--------------------------------------------------------------------------
        public function get listener():UIComponent
        {
            return master;
        }
		//--------------------------------------------------------------------------
		//
		//  Class methods
		//
		//--------------------------------------------------------------------------
		
		/**
		 *  Enables accessibility in the class.
		 *  <p>This method is called by application startup code
		 *  that is autogenerated by the MXML compiler.
		 *  Afterwards, when instances are initialized,
		 *  their <code>accessibilityImplementation</code> property
		 *  will be set to an instance of this class.</p>
		 */
		public static function enableAccessibility():void
		{
            UIComponent.createAccessibilityImplementation = createAccessibilityImplementation;
			//Button.createAccessibilityImplementation = createAccessibilityImplementation;
		}
		
		/**
		 *  @private
		 *  Creates a AccessibilityImplementation object.
		 *  This method is called from UIComponent's initializeAccessibility() method.
		 */
		mx_internal static function createAccessibilityImplementation(component:UIComponent):void
		{
			component.accessibilityImplementation = new CustomAccImpl(component);
		}
		
		//--------------------------------------------------------------------------
		//
		//  Constructor
		//
		//--------------------------------------------------------------------------
		
		/**
		 *  Constructor.
		 *
		 *  @param master The UIComponent instance that this AccImpl instance
		 *  is making accessible.
		 */
		public function CustomAccImpl(master:UIComponent)
		{
			super(master);
			role = 0x9;
		}
		
		//--------------------------------------------------------------------------
		//
		//  Overridden properties: AccImpl
		//
		//--------------------------------------------------------------------------
		
		//--------------------------------------------------------------------------
		//
		//  Overridden methods: AccessibilityImplementation
		//
		//--------------------------------------------------------------------------
		
		/**
		 *  @private
		 *  IAccessible method for returning the state of the Component.
		 *  States are predefined for all the components in MSAA.
		 *  @param childID uint
		 *  @return State uint
		 */
		override public function get_accState(childID:uint):uint
		{
			return  0x00000002;
		}
		
		/**
		 *  @private
		 */
		override public function get_accDefaultAction(childID:uint):String
		{
			return "none"; //"Press"
		}
		
		override public function accLocation(childID:uint):*
		{
			return null;
		}
		
		override public function get_accName(childID:uint):String
		{
			return master.accessibilityProperties.name;	
		}
		
		//--------------------------------------------------------------------------
		//
		//  Overridden methods: AccImpl
		//
		//--------------------------------------------------------------------------
		
		//--------------------------------------------------------------------------
		//
		//  Overridden event handlers: AccImpl
		//
		//--------------------------------------------------------------------------
		
		/**
		 *  @private
		 *  Override the generic event handler.
		 *  All AccImpl must implement this to listen for events from its master component. 
		 */
		override protected function eventHandler(event:Event):void
		{
			// Let AccImpl class handle the events
			// that all accessible UIComponents understand.
			$eventHandler(event);
		}
	}
	
}
